# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '20201204-Realm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift'
  # Pods for 20201204-Realm

  target '20201204-RealmTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '20201204-RealmUITests' do
    # Pods for testing
  end

end
