# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '20201202-BancoDeDados' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 20201202-BancoDeDados
pod 'NAMDatabase'
pod 'RealmSwift'

  target '20201202-BancoDeDadosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '20201202-BancoDeDadosUITests' do
    # Pods for testing
  end

end
